---
# tasks file for satellite_install


  - name: install the satellite rpm's
    yum:
      name: "{{ satellite_rpms }}"
      state: installed
    notify: start and enable chrony

  - name: copy over the template satellite.answer.yml
    template:
      src: satellite-answer.yml.j2
      dest: /etc/foreman-installer/scenarios.d/satellite-answers.yml
